"""Nelson-Siegel fitting.

The decisive test is recovery: build a curve from known betas, fit it, and
demand the betas back. If that holds, the design matrix and the sign convention
are both right, and every downstream number inherits their correctness.
"""

from __future__ import annotations

import numpy as np
import pytest

from findynamics.engines.rates.nelson_siegel import (
    DEFAULT_LAMBDA,
    design_matrix,
    fit_curve,
    select_lambda,
)

TENORS = np.array([0.0833, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 20.0, 30.0])


def synthetic(b0: float, b1: float, b2: float, lambda_: float = DEFAULT_LAMBDA, tenors=TENORS):
    """Yields generated by the model itself, for exact recovery."""
    return design_matrix(tenors, lambda_) @ np.array([b0, b1, b2])


@pytest.mark.parametrize(
    ("b0", "b1", "b2"),
    [
        (4.0, -1.5, 2.0),  # normal upward-sloping curve with a hump
        (5.2, 1.8, -1.0),  # inverted: short rate above the long end
        (2.0, 0.0, 0.0),  # flat
        (0.5, -0.2, 0.1),  # zero-lower-bound era
        (8.0, 2.5, 3.0),  # 1980s levels, deeply inverted
    ],
)
def test_recovers_known_betas(b0, b1, b2):
    fit = fit_curve(TENORS, synthetic(b0, b1, b2))

    assert fit is not None
    assert fit.level == pytest.approx(b0, abs=1e-8)
    assert fit.beta1 == pytest.approx(b1, abs=1e-8)
    assert fit.curvature == pytest.approx(b2, abs=1e-8)
    assert fit.rmse == pytest.approx(0.0, abs=1e-9)
    assert fit.n_tenors == len(TENORS)


def test_slope_is_negative_beta1_so_upward_sloping_reads_positive():
    """The published slope must be long-minus-short, not b1's raw sign."""
    upward = fit_curve(TENORS, synthetic(4.0, -1.5, 0.0))
    inverted = fit_curve(TENORS, synthetic(4.0, 1.5, 0.0))

    assert upward is not None and inverted is not None
    assert upward.slope > 0
    assert inverted.slope < 0
    assert upward.slope == pytest.approx(-upward.beta1)


def test_level_is_the_long_end_and_level_plus_beta1_is_the_short_end():
    fit = fit_curve(TENORS, synthetic(4.0, -1.5, 2.0))
    assert fit is not None
    assert fit.yield_at(0.0) == pytest.approx(fit.level + fit.beta1, abs=1e-9)
    assert fit.yield_at(200.0) == pytest.approx(fit.level, abs=1e-2)


def test_curvature_moves_the_belly_and_leaves_the_ends_alone():
    """Otherwise it is not curvature — it is a second level or slope factor."""
    flat = fit_curve(TENORS, synthetic(4.0, -1.0, 0.0))
    humped = fit_curve(TENORS, synthetic(4.0, -1.0, 3.0))
    assert flat is not None and humped is not None

    belly = humped.yield_at(2.5) - flat.yield_at(2.5)
    assert belly > 0.5

    # Exactly zero at tau=0; at the long end the loading decays as 1/(lambda*tau)
    # rather than vanishing, so the claim is that it is negligible beside the
    # belly effect, not that it is identically zero.
    assert humped.yield_at(0.0) == pytest.approx(flat.yield_at(0.0), abs=1e-9)
    assert abs(humped.yield_at(300.0) - flat.yield_at(300.0)) < 0.05 * belly


def test_recovers_betas_approximately_under_quote_noise():
    rng = np.random.default_rng(20260730)
    truth = (4.0, -1.5, 2.0)
    noisy = synthetic(*truth) + rng.normal(0.0, 0.02, size=len(TENORS))

    fit = fit_curve(TENORS, noisy)

    assert fit is not None
    assert fit.level == pytest.approx(truth[0], abs=0.05)
    assert fit.beta1 == pytest.approx(truth[1], abs=0.1)
    assert fit.curvature == pytest.approx(truth[2], abs=0.2)
    assert 0.0 < fit.rmse < 0.05


def test_design_matrix_handles_zero_maturity():
    """The decay term is 0/0 at tau=0; the limit is 1, not NaN."""
    loadings = design_matrix(np.array([0.0]), DEFAULT_LAMBDA)
    assert np.all(np.isfinite(loadings))
    assert loadings[0, 0] == pytest.approx(1.0)
    assert loadings[0, 1] == pytest.approx(1.0)
    assert loadings[0, 2] == pytest.approx(0.0)


def test_rejects_a_non_positive_lambda():
    with pytest.raises(ValueError, match="lambda must be positive"):
        design_matrix(TENORS, 0.0)


def test_too_few_tenors_returns_none_rather_than_raising():
    """A thin day is normal — holidays, and DGS1MO starts in 2001."""
    assert fit_curve(TENORS[:4], synthetic(4.0, -1.5, 2.0)[:4]) is None


def test_min_tenors_is_configurable():
    yields = synthetic(4.0, -1.5, 2.0)
    assert fit_curve(TENORS[:4], yields[:4], min_tenors=3) is not None


def test_nan_yields_are_dropped_not_propagated():
    yields = synthetic(4.0, -1.5, 2.0).copy()
    yields[0] = np.nan
    yields[3] = np.nan

    fit = fit_curve(TENORS, yields)

    assert fit is not None
    assert fit.n_tenors == len(TENORS) - 2
    assert fit.level == pytest.approx(4.0, abs=1e-6)


def test_mismatched_lengths_are_a_programming_error():
    with pytest.raises(ValueError, match="differ in length"):
        fit_curve(TENORS, np.array([1.0, 2.0]))


class TestLambdaSelection:
    def test_finds_the_lambda_that_generated_the_curves(self):
        true_lambda = 0.4
        curves = [
            (TENORS, synthetic(4.0, -1.5, 2.0, true_lambda)),
            (TENORS, synthetic(4.2, -1.2, 1.5, true_lambda)),
            (TENORS, synthetic(3.8, -1.8, 2.4, true_lambda)),
        ]

        chosen, scores = select_lambda(curves, [0.2, 0.3, 0.4, 0.5, 0.8, 1.2])

        assert chosen == pytest.approx(true_lambda)
        assert scores[true_lambda] < scores[0.8]

    def test_reports_the_whole_grid_so_a_refit_is_auditable(self):
        grid = [0.3, 0.609, 0.9]
        _, scores = select_lambda([(TENORS, synthetic(4.0, -1.5, 2.0))], grid)
        assert sorted(scores) == sorted(grid)

    def test_falls_back_to_the_convention_when_nothing_fits(self):
        """No usable curve must not abort a refit; the previous default stands."""
        chosen, scores = select_lambda([(TENORS[:2], np.array([1.0, 2.0]))], [0.3, 0.6])
        assert chosen == DEFAULT_LAMBDA
        assert scores == {}

    def test_an_empty_grid_is_rejected(self):
        with pytest.raises(ValueError, match="lambda grid is empty"):
            select_lambda([(TENORS, synthetic(4.0, -1.5, 2.0))], [])
